# Data Exploration

This notebook is a starting point for exploring the MRI dataset once it is placed in `data/raw/`.

In [1]:
import pandas as pd

In [8]:

file_path = "../data/raw/cln1/cln01_patient_table_jul25.xlsx"

df = pd.read_excel(
    file_path,
    header=9
)

print(df.head())
print(df.columns.tolist())
print(df.shape)

    Patient ID REL #  Patient ID2 Mutation #      Alleles  \
0  Pa-cln1.001   NaN  1_Vesa_1995   cln1.001  p.Arg122Trp
1  Pa-cln1.001   NaN  1_Vesa_1995   cln1.001  p.Arg122Trp
2  Pa-cln1.002   NaN  2_Vesa_1995   cln1.001  p.Arg122Trp
3  Pa-cln1.002   NaN  2_Vesa_1995   cln1.001  p.Arg122Trp
4  Pa-cln1.003   NaN  3_Vesa_1995   cln1.001  p.Arg122Trp

  Changes in same gene Changes in other genes NCL Phenotype or other disease  \
0                  NaN                    NaN                      infantile
1                  NaN                    NaN                      infantile
2                  NaN                    NaN                      infantile
3                  NaN                    NaN                      infantile
4                  NaN                    NaN                      infantile

  Age at onset (y) Histology Country of origin other ethnic detail  \
0              NaN       NaN           Finland                 NaN
1              NaN       NaN           Finland                 NaN
2              NaN       NaN           Finland                 NaN
3              NaN       NaN           Finland                 NaN
4              NaN       NaN           Finland                 NaN

  Country of Residence          Reference     PMID                   Notes
0                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
1                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
2                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
3                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
4                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
['Patient ID', 'REL #', 'Patient ID2', 'Mutation #', 'Alleles', 'Changes in same gene', 'Changes in other genes', 'NCL Phenotype or other disease', 'Age at onset (y)', 'Histology', 'Country of origin', 'other ethnic detail', 'Country of Residence', 'Reference', 'PMID', 'Notes']
(535, 16)

In [10]:
df = pd.read_excel(
    file_path,
    header=9
)

In [11]:
print(df.head())

    Patient ID REL #  Patient ID2 Mutation #      Alleles  \
0  Pa-cln1.001   NaN  1_Vesa_1995   cln1.001  p.Arg122Trp
1  Pa-cln1.001   NaN  1_Vesa_1995   cln1.001  p.Arg122Trp
2  Pa-cln1.002   NaN  2_Vesa_1995   cln1.001  p.Arg122Trp
3  Pa-cln1.002   NaN  2_Vesa_1995   cln1.001  p.Arg122Trp
4  Pa-cln1.003   NaN  3_Vesa_1995   cln1.001  p.Arg122Trp

  Changes in same gene Changes in other genes NCL Phenotype or other disease  \
0                  NaN                    NaN                      infantile
1                  NaN                    NaN                      infantile
2                  NaN                    NaN                      infantile
3                  NaN                    NaN                      infantile
4                  NaN                    NaN                      infantile

  Age at onset (y) Histology Country of origin other ethnic detail  \
0              NaN       NaN           Finland                 NaN
1              NaN       NaN           Finland                 NaN
2              NaN       NaN           Finland                 NaN
3              NaN       NaN           Finland                 NaN
4              NaN       NaN           Finland                 NaN

  Country of Residence          Reference     PMID                   Notes
0                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
1                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
2                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
3                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect
4                  NaN  Vesa et al., 1995  7637805  Finnish Founder effect

In [12]:
print(df.columns.tolist())

['Patient ID', 'REL #', 'Patient ID2', 'Mutation #', 'Alleles', 'Changes in same gene', 'Changes in other genes', 'NCL Phenotype or other disease', 'Age at onset (y)', 'Histology', 'Country of origin', 'other ethnic detail', 'Country of Residence', 'Reference', 'PMID', 'Notes']

In [13]:
print(df.shape)

(535, 16)

In [15]:
for i, column in enumerate(df.columns):
    print(i, ":", column)
    df.info()

0 : Patient ID
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
1 : REL #
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
2 : Patient ID2
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
3 : Mutation #
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
4 : Alleles
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
5 : Changes in same gene
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
6 : Changes in other genes
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
7 : NCL Phenotype or other disease
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
8 : Age at onset (y)
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
9 : Histology
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
10 : Country of origin
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
11 : other ethnic detail
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
12 : Country of Residence
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
13 : Reference
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
14 : PMID
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB
15 : Notes
<class 'pandas.DataFrame'>
RangeIndex: 535 entries, 0 to 534
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Patient ID                      520 non-null    str
 1   REL #                           44 non-null     str
 2   Patient ID2                     463 non-null    object
 3   Mutation #                      488 non-null    str
 4   Alleles                         516 non-null    str
 5   Changes in same gene            2 non-null      str
 6   Changes in other genes          2 non-null      str
 7   NCL Phenotype or other disease  348 non-null    str
 8   Age at onset (y)                213 non-null    object
 9   Histology                       161 non-null    str
 10  Country of origin               473 non-null    str
 11  other ethnic detail             27 non-null     str
 12  Country of Residence            110 non-null    str
 13  Reference                       510 non-null    str
 14  PMID                            480 non-null    object
 15  Notes                           202 non-null    str
dtypes: object(3), str(13)
memory usage: 67.0+ KB

In [18]:
important_columns = [
    "Patient ID",
    "Mutation #",
    "Alleles",
    "NCL Phenotype or other disease",
    "Age at onset (y)",
    "Histology"
]

for column in important_columns:
    print("\n" + "=" * 60)
    print("COLUMN:", column)
    print("=" * 60)
    print(df[column].dropna().unique()[:20])

============================================================
COLUMN: Patient ID
============================================================
<StringArray>
['Pa-cln1.001', 'Pa-cln1.002', 'Pa-cln1.003', 'Pa-cln1.004', 'Pa-cln1.005',
 'Pa-cln1.006', 'Pa-cln1.007', 'Pa-cln1.008', 'Pa-cln1.009', 'Pa-cln1.010',
 'Pa-cln1.011', 'Pa-cln1.012', 'Pa-cln1.013', 'Pa-cln1.014', 'Pa-cln1.015',
 'Pa-cln1.016', 'Pa-cln1.017', 'Pa-cln1.018', 'Pa-cln1.019', 'Pa-cln1.020']
Length: 20, dtype: str

============================================================
COLUMN: Mutation #
============================================================
<StringArray>
['cln1.001', 'cln1.002', 'cln1.009', 'cln1.004', 'cln1.006', 'cln1.005',
 'cln1.008', 'cln1.017', 'cln1.015', 'cln1.014', 'cln1.012', 'cln1.011',
 'cln1.020', 'cln1.018', 'cln1.013', 'cln1.010', 'cln1.016', 'cln1.023',
 'cln1.021', 'cln1.022']
Length: 20, dtype: str

============================================================
COLUMN: Alleles
============================================================
<StringArray>
[      'p.Arg122Trp',       'null allele',    'not identified',
          'p.Lys55*',       'p.(Arg151*)',      '(p.Thr75Pro)',
     'p.(Leu219Gln)',      'p.(Asp79Gly)',        'p.(Leu10*)',
     'p.(Val181Met)',       'p.(Arg164*)', 'p.(Met133Argfs*4)',
      'p.(Gly42Glu)',      'p.(His39Gln)',        'c.727-2A>T',
     'p.(Glu184Lys)',     'p.(Tyr109Asp)',            'c.3G>A',
     'p.(Gln177Glu)',       'p.(Trp296*)']
Length: 20, dtype: str

============================================================
COLUMN: NCL Phenotype or other disease
============================================================
<StringArray>
[             'infantile',               'juvenile',         'late infantile',
                  'adult',    'Fragility fractures', 'infantile / congenital',
             'congenital']
Length: 7, dtype: str

============================================================
COLUMN: Age at onset (y)
============================================================
[6 8 7 10 0.3 0.5 0.7 1 1.5 3.5 5 7.5 0.8 2.2 1.25 3 3.2 31 38 4]

============================================================
COLUMN: Histology
============================================================
<StringArray>
[                                 'GROD',
                             'GROD / CV',
                        'GROD / CV / FP',
                                    'CL',
                  'NA (sister has GROD)',
                             'GROD (FP)',
                         'not performed',
                        'GROD / CV / RL',
 'granular osmiophilic deposit (muscle)']
Length: 9, dtype: str

In [19]:
print("Total rows:", len(df))
print("Non-null Patient IDs:", df["Patient ID"].notna().sum())
print("Unique Patient IDs:", df["Patient ID"].nunique())

Total rows: 535
Non-null Patient IDs: 520
Unique Patient IDs: 262

In [17]:
for i, column in enumerate(df.columns):
    print(i, ":", repr(column))

0 : 'Patient ID'
1 : 'REL #'
2 : 'Patient ID2'
3 : 'Mutation #'
4 : 'Alleles'
5 : 'Changes in same gene'
6 : 'Changes in other genes'
7 : 'NCL Phenotype or other disease'
8 : 'Age at onset (y)'
9 : 'Histology'
10 : 'Country of origin'
11 : 'other ethnic detail'
12 : 'Country of Residence'
13 : 'Reference'
14 : 'PMID'
15 : 'Notes'

In [20]:
patient_counts = df["Patient ID"].value_counts()

print(patient_counts.head(20))

Patient ID
Pa-cln1.001    2
Pa-cln1.002    2
Pa-cln1.003    2
Pa-cln1.004    2
Pa-cln1.005    2
Pa-cln1.006    2
Pa-cln1.007    2
Pa-cln1.008    2
Pa-cln1.009    2
Pa-cln1.010    2
Pa-cln1.011    2
Pa-cln1.012    2
Pa-cln1.013    2
Pa-cln1.014    2
Pa-cln1.015    2
Pa-cln1.016    2
Pa-cln1.017    2
Pa-cln1.018    2
Pa-cln1.019    2
Pa-cln1.020    2
Name: count, dtype: int64

In [21]:
df[df["Patient ID"] == "Pa-cln1.001"].T

                                                     0                       1
Patient ID                                 Pa-cln1.001             Pa-cln1.001
REL #                                              NaN                     NaN
Patient ID2                                1_Vesa_1995             1_Vesa_1995
Mutation #                                    cln1.001                cln1.001
Alleles                                    p.Arg122Trp             p.Arg122Trp
Changes in same gene                               NaN                     NaN
Changes in other genes                             NaN                     NaN
NCL Phenotype or other disease               infantile               infantile
Age at onset (y)                                   NaN                     NaN
Histology                                          NaN                     NaN
Country of origin                              Finland                 Finland
other ethnic detail                                NaN                     NaN
Country of Residence                               NaN                     NaN
Reference                            Vesa et al., 1995       Vesa et al., 1995
PMID                                           7637805                 7637805
Notes                           Finnish Founder effect  Finnish Founder effect

In [22]:
phenotype_col = "NCL Phenotype or other disease"

print("Non-null values:", df[phenotype_col].notna().sum())
print("Unique values:", df[phenotype_col].nunique())

print("\nFirst 30 unique values:")
for value in df[phenotype_col].dropna().unique()[:30]:
    print("-", value)

Non-null values: 348
Unique values: 7

First 30 unique values:
- infantile
- juvenile
- late infantile
- adult
- Fragility fractures
- infantile / congenital
- congenital

In [23]:
age_col = "Age at onset (y)"

print("Non-null values:", df[age_col].notna().sum())
print("Unique values:", df[age_col].nunique())

print("\nFirst 30 unique values:")
for value in df[age_col].dropna().unique()[:30]:
    print("-", value)

Non-null values: 213
Unique values: 31

First 30 unique values:
- 6
- 8
- 7
- 10
- 0.3
- 0.5
- 0.7
- 1
- 1.5
- 3.5
- 5
- 7.5
- 0.8
- 2.2
- 1.25
- 3
- 3.2
- 31
- 38
- 4
- 2
- 2.5
- <1
- 24
- 0.4
- 1.2
- 1.1
- 9
- 1.6
- 1.3

In [24]:
patient_counts = df["Patient ID"].value_counts()

print(patient_counts.head(20))

Patient ID
Pa-cln1.001    2
Pa-cln1.002    2
Pa-cln1.003    2
Pa-cln1.004    2
Pa-cln1.005    2
Pa-cln1.006    2
Pa-cln1.007    2
Pa-cln1.008    2
Pa-cln1.009    2
Pa-cln1.010    2
Pa-cln1.011    2
Pa-cln1.012    2
Pa-cln1.013    2
Pa-cln1.014    2
Pa-cln1.015    2
Pa-cln1.016    2
Pa-cln1.017    2
Pa-cln1.018    2
Pa-cln1.019    2
Pa-cln1.020    2
Name: count, dtype: int64

In [25]:
df[df["Patient ID"] == "PATIENT_ID_HERE"].T

Empty DataFrame
Columns: []
Index: [Patient ID, REL #, Patient ID2, Mutation #, Alleles, Changes in same gene, Changes in other genes, NCL Phenotype or other disease, Age at onset (y), Histology, Country of origin, other ethnic detail, Country of Residence, Reference, PMID, Notes]

In [26]:
df[df["Patient ID"] == "Pa-cln1.001"].T

                                                     0                       1
Patient ID                                 Pa-cln1.001             Pa-cln1.001
REL #                                              NaN                     NaN
Patient ID2                                1_Vesa_1995             1_Vesa_1995
Mutation #                                    cln1.001                cln1.001
Alleles                                    p.Arg122Trp             p.Arg122Trp
Changes in same gene                               NaN                     NaN
Changes in other genes                             NaN                     NaN
NCL Phenotype or other disease               infantile               infantile
Age at onset (y)                                   NaN                     NaN
Histology                                          NaN                     NaN
Country of origin                              Finland                 Finland
other ethnic detail                                NaN                     NaN
Country of Residence                               NaN                     NaN
Reference                            Vesa et al., 1995       Vesa et al., 1995
PMID                                           7637805                 7637805
Notes                           Finnish Founder effect  Finnish Founder effect

In [1]:
import pandas as pd
from pathlib import Path
import os

In [2]:
BASE_PATH = Path("../data/raw")

print("Base path:", BASE_PATH.resolve())

Base path: C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI\data\raw

In [3]:
files = {
    "CLN1_Patient": BASE_PATH / "cln1" / "cln01_patient_table_jul25.xlsx",
    "CLN1_Mutation": BASE_PATH / "cln1" / "cln01_mutation_table_jul25.xlsx",

    "CLN2_Patient": BASE_PATH / "cln2" / "cln02_patient_table_jan26.xlsx",
    "CLN2_Mutation": BASE_PATH / "cln2" / "cln02_mutation_table_jan26.xlsx",

    "CLN3_Patient": BASE_PATH / "cln3" / "cln03_patient_table_feb26.xlsx",
    "CLN3_Mutation": BASE_PATH / "cln3" / "cln03_mutation_table_feb26.xlsx"
}

for name, path in files.items():
    print(name)
    print("Exists:", path.exists())
    print("Path:", path)
    print("-" * 60)

CLN1_Patient
Exists: True
Path: ..\data\raw\cln1\cln01_patient_table_jul25.xlsx
------------------------------------------------------------
CLN1_Mutation
Exists: True
Path: ..\data\raw\cln1\cln01_mutation_table_jul25.xlsx
------------------------------------------------------------
CLN2_Patient
Exists: True
Path: ..\data\raw\cln2\cln02_patient_table_jan26.xlsx
------------------------------------------------------------
CLN2_Mutation
Exists: True
Path: ..\data\raw\cln2\cln02_mutation_table_jan26.xlsx
------------------------------------------------------------
CLN3_Patient
Exists: True
Path: ..\data\raw\cln3\cln03_patient_table_feb26.xlsx
------------------------------------------------------------
CLN3_Mutation
Exists: True
Path: ..\data\raw\cln3\cln03_mutation_table_feb26.xlsx
------------------------------------------------------------

In [4]:
for name, path in files.items():
    excel_file = pd.ExcelFile(path)

    print("\n" + "=" * 70)
    print(name)
    print("=" * 70)
    print("Sheets:", excel_file.sheet_names)

======================================================================
CLN1_Patient
======================================================================
Sheets: ['CLN1 Patient Database']

======================================================================
CLN1_Mutation
======================================================================
Sheets: ['CLN1 mutation datasheet', 'Summary sheet']

======================================================================
CLN2_Patient
======================================================================
Sheets: ['patients']

======================================================================
CLN2_Mutation
======================================================================
Sheets: ['mutation data', 'Summary statistics', 'Affected residues', 'Other reports']

======================================================================
CLN3_Patient
======================================================================
Sheets: ['Patient data', 'Sheet1']

======================================================================
CLN3_Mutation
======================================================================
Sheets: ['mutation data ', 'Summary statistics', 'status uncertain']

In [6]:
dataset_info = {}

for name, path in files.items():

    print("\n" + "=" * 80)
    print("DATASET:", name)
    print("=" * 80)

    # Read first sheet
    df_temp = pd.read_excel(path)

    # Store information
    dataset_info[name] = {
        "shape": df_temp.shape,
        "columns": df_temp.columns.tolist()
    }

    print("\nSHAPE:")
    print(df_temp.shape)

    print("\nCOLUMNS:")
    for i, col in enumerate(df_temp.columns):
        print(f"{i}: {repr(col)}")

    print("\nFIRST 10 ROWS:")
    display(df_temp.head(10))

    print("\nMISSING VALUES:")
    print(df_temp.isnull().sum())

    print("\nEXACT DUPLICATE ROWS:")
    print(df_temp.duplicated().sum())
    print("\n\n" + "=" * 80)
print("FINAL DATASET SUMMARY")
print("=" * 80)

for name, info in dataset_info.items():
    print("\nDATASET:", name)
    print("Shape:", info["shape"])
    print("Columns:")
    print(info["columns"])

================================================================================
DATASET: CLN1_Patient
================================================================================

SHAPE:
(544, 16)

COLUMNS:
0: 'Gene ID'
1: 'Unnamed: 1'
2: 'Unnamed: 2'
3: 5538
4: 'Unnamed: 4'
5: 'Unnamed: 5'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'

FIRST 10 ROWS:

,Gene ID,Unnamed: 1,Unnamed: 2,5538,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Chromosomal Location,NaN,NaN,1p32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Genomic RefSeqGene,NaN,NaN,NG_009192.1,31761 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Transcript,NaN,NaN,NM_000310.4,2284 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Protein RefSeq,NaN,NaN,NP_000301.1,306 aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No patients,NaN,NaN,258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No. families,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Additional notes,NaN,NaN,Updated Jul-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Patient ID,REL #,Patient ID2,Mutation #,Alleles,Changes in same gene,Changes in other genes,NCL Phenotype or other disease,Age at onset (y),Histology,Country of origin,other ethnic detail,Country of Residence,Reference,PMID,Notes
9,Pa-cln1.001,NaN,1_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect

MISSING VALUES:
Gene ID         16
Unnamed: 1     499
Unnamed: 2      80
5538            48
Unnamed: 4      24
Unnamed: 5     541
Unnamed: 6     541
Unnamed: 7     195
Unnamed: 8     330
Unnamed: 9     382
Unnamed: 10     70
Unnamed: 11    516
Unnamed: 12    433
Unnamed: 13     33
Unnamed: 14     63
Unnamed: 15    341
dtype: int64

EXACT DUPLICATE ROWS:
151


================================================================================

================================================================================
DATASET: CLN1_Mutation
================================================================================

SHAPE:
(119, 14)

COLUMNS:
0: 'Gene ID'
1: 'Unnamed: 1'
2: 'Unnamed: 2'
3: 5538
4: 'Unnamed: 4'
5: 'Notes'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'

FIRST 10 ROWS:

,Gene ID,Unnamed: 1,Unnamed: 2,5538,Unnamed: 4,Notes,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Chromosomal Location,NaN,NaN,1p32,NaN,Variants are included on the basis that they o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Genomic RefSeqGene,NaN,NaN,NG_009192.1,31761 bp,"1) if the allele frequency is known, it is <5%;",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Transcript,NaN,NaN,NM_000310.4,2284 bp,2) there is no other molecular basis for the d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Protein RefSeq,NaN,NaN,NP_000301.1,306 aa,3) they are indicated pathogenic or likely pat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,4) reduction in PPT1 enzyme activity was reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Identifier,Location,Nucleotide change,Amino acid change,Type of Mutation - DNA,Additional mutation information,Predicted functional effect,clinvar classification,rs number,contig position (GRCh38.p7),PMID,References,Original description,Others notes
8,cln1.001,Exon 04,c.364A>T,p.(Arg122Trp),substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
9,cln1.002,Exon 02,c.163A>T,p.(Lys55*),substitution,nonsense,NaN,Likely pathogenic,rs386833633,40092469,7637805,Vesa et al. 1995,NaN,NaN

MISSING VALUES:
Gene ID         12
Unnamed: 1      20
Unnamed: 2      20
5538            30
Unnamed: 4      21
Notes           16
Unnamed: 6      58
Unnamed: 7      41
Unnamed: 8      42
Unnamed: 9      20
Unnamed: 10     32
Unnamed: 11     20
Unnamed: 12    101
Unnamed: 13     95
dtype: int64

EXACT DUPLICATE ROWS:
10


================================================================================

================================================================================
DATASET: CLN2_Patient
================================================================================

SHAPE:
(1184, 20)

COLUMNS:
0: 'Gene Symbol'
1: 'Unnamed: 1'
2: 'Unnamed: 2'
3: 'CLN2/TPP1'
4: 'Unnamed: 4'
5: 'Unnamed: 5'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'
16: 'Unnamed: 16'
17: 'Unnamed: 17'
18: 'Unnamed: 18'
19: 'Unnamed: 19'

FIRST 10 ROWS:

,Gene Symbol,Unnamed: 1,Unnamed: 2,CLN2/TPP1,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Gene ID,NaN,NaN,1200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chromosomal Location,NaN,NaN,11p15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Genomic RefSeqGene,NaN,NaN,NG_008653.1,13696 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Transcript RefSeq,NaN,NaN,NM_000391.4,3492 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Protein RefSeq,NaN,NaN,NP_000382.3,563 aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No. of patients,NaN,NaN,578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,No. of families with >1 individual in this table,NaN,NaN,37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,No. of patients in this table that are related,NaN,NaN,86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,No. of patients with no relation in this table,NaN,NaN,492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Additional Notes,NaN,NaN,Updated Jan26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

MISSING VALUES:
Gene Symbol      12
Unnamed: 1     1011
Unnamed: 2      105
CLN2/TPP1        89
Unnamed: 4       31
Unnamed: 5     1088
Unnamed: 6     1161
Unnamed: 7      343
Unnamed: 8      519
Unnamed: 9      869
Unnamed: 10     139
Unnamed: 11    1139
Unnamed: 12     976
Unnamed: 13      27
Unnamed: 14     117
Unnamed: 15     848
Unnamed: 16    1099
Unnamed: 17    1179
Unnamed: 18    1182
Unnamed: 19    1140
dtype: int64

EXACT DUPLICATE ROWS:
249


================================================================================

================================================================================
DATASET: CLN2_Mutation
================================================================================

SHAPE:
(205, 16)

COLUMNS:
0: 'Gene Symbol'
1: 'CLN2/TPP1'
2: 'Unnamed: 2'
3: 'Unnamed: 3'
4: 'Unnamed: 4'
5: 'Notes'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'

FIRST 10 ROWS:

,Gene Symbol,CLN2/TPP1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Notes,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,Gene ID,1200,NaN,NaN,NaN,Variants are included on the basis that they o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chromosomal Location,11p15,NaN,NaN,NaN,"1) if the allele frequency is known, it is <5%;",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Genomic RefSeqGene,NG_008653.1,NaN,13696 bp,NaN,2) there is no other molecular basis for the d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Transcript RefSeq,NM_000391.4,NaN,3540 bp,NaN,3) they are indicated pathogenic or likely pat...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Protein RefSeq,NP_000382.3,NaN,563 aa,NaN,4) reduction in TPP1 enzyme activity was reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,The orientation of the gene is on the negative...,NaN,NaN,NaN,NaN,See fourth tab for reported variants occurring...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,See second tab of spreadsheet for statistics o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,See third tab for list of affected residues,NaN,NaN,NaN,NaN,Recommended Mutation nomenclature followed (ht...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,Polyphen and/or SIFT used to predict functiona...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,"For intron variants, HSF was used for all vari...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

MISSING VALUES:
Gene Symbol      9
CLN2/TPP1       13
Unnamed: 2      18
Unnamed: 3      40
Unnamed: 4      19
Notes            7
Unnamed: 6      88
Unnamed: 7     174
Unnamed: 8     132
Unnamed: 9     131
Unnamed: 10     20
Unnamed: 11     17
Unnamed: 12     55
Unnamed: 13    188
Unnamed: 14    175
Unnamed: 15    197
dtype: int64

EXACT DUPLICATE ROWS:
2


================================================================================

================================================================================
DATASET: CLN3_Patient
================================================================================

SHAPE:
(621, 17)

COLUMNS:
0: 'Gene Symbol'
1: 'CLN3'
2: 'Unnamed: 2'
3: 'Unnamed: 3'
4: 'Unnamed: 4'
5: 'Unnamed: 5'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'
16: 'Unnamed: 16'

FIRST 10 ROWS:

,Gene Symbol,CLN3,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Gene ID,1201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chromosomal Location,16p12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Genomic RefSeqGene,NG_008654.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Transcript RefSeq,NM_001042432.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Protein RefSeq,NP_000077.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,No. patients,298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,No. families,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Additional notes,Note that the exons/introns are numbered accor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,c.1211 variant previously numbered as cln3.028...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

MISSING VALUES:
Gene Symbol      9
CLN3           486
Unnamed: 2     112
Unnamed: 3      84
Unnamed: 4      81
Unnamed: 5     608
Unnamed: 6     614
Unnamed: 7     172
Unnamed: 8     364
Unnamed: 9     503
Unnamed: 10    148
Unnamed: 11    580
Unnamed: 12    542
Unnamed: 13     25
Unnamed: 14     79
Unnamed: 15    355
Unnamed: 16    562
dtype: int64

EXACT DUPLICATE ROWS:
110


================================================================================

================================================================================
DATASET: CLN3_Mutation
================================================================================

SHAPE:
(160, 18)

COLUMNS:
0: 'Gene Symbol'
1: 'CLN3'
2: 'Unnamed: 2'
3: 'Unnamed: 3'
4: 'Unnamed: 4'
5: 'Unnamed: 5'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'
16: 'Unnamed: 16'
17: 'Unnamed: 17'

FIRST 10 ROWS:

,Gene Symbol,CLN3,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,Gene ID,1201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Chromosomal Location,16p12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Genomic RefSeqGene,NG_008654.2,32641 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Transcript RefSeq,NM_001042432.2,1685 bp,NM_000086.2,1879 bp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Protein RefSeq,NP_001035897.1,438 aa,NP_000077.1,438 aa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,See second tab of spreadsheet for statistics o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Additional notes,Note that the exons/introns are numbered accor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Intron/exon numbering updated wrt reference se...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Updated Feb26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

MISSING VALUES:
Gene Symbol     14
CLN3            22
Unnamed: 2      27
Unnamed: 3      63
Unnamed: 4      29
Unnamed: 5      29
Unnamed: 6      40
Unnamed: 7      89
Unnamed: 8      65
Unnamed: 9      69
Unnamed: 10     68
Unnamed: 11     31
Unnamed: 12     28
Unnamed: 13     47
Unnamed: 14    140
Unnamed: 15    113
Unnamed: 16    146
Unnamed: 17    159
dtype: int64

EXACT DUPLICATE ROWS:
11


================================================================================
FINAL DATASET SUMMARY
================================================================================

DATASET: CLN1_Patient
Shape: (544, 16)
Columns:
['Gene ID', 'Unnamed: 1', 'Unnamed: 2', 5538, 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

DATASET: CLN1_Mutation
Shape: (119, 14)
Columns:
['Gene ID', 'Unnamed: 1', 'Unnamed: 2', 5538, 'Unnamed: 4', 'Notes', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

DATASET: CLN2_Patient
Shape: (1184, 20)
Columns:
['Gene Symbol', 'Unnamed: 1', 'Unnamed: 2', 'CLN2/TPP1', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19']

DATASET: CLN2_Mutation
Shape: (205, 16)
Columns:
['Gene Symbol', 'CLN2/TPP1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Notes', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15']

DATASET: CLN3_Patient
Shape: (621, 17)
Columns:
['Gene Symbol', 'CLN3', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16']

DATASET: CLN3_Mutation
Shape: (160, 18)
Columns:
['Gene Symbol', 'CLN3', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17']