# Preprocessing

This notebook will be used to validate image loading, resizing, normalization, and dataset checks.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
BASE_DIR = Path(r"C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI")

DATA_DIR = BASE_DIR / "data" / "raw"

print(DATA_DIR)

C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI\data\raw

In [3]:
import pandas as pd

print("Pandas imported successfully")

Pandas imported successfully

In [4]:
BASE_DIR = Path(r"C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI")

DATA_DIR = BASE_DIR / "data" / "raw"

print("Project directory:", BASE_DIR)
print("Data directory:", DATA_DIR)

Project directory: C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI
Data directory: C:\Users\Adithya\OneDrive\Desktop\Batten_Disease_Prediction_Using_AI\data\raw

In [5]:
files = {
    "CLN1_Patient": DATA_DIR / "cln1" / "cln01_patient_table_jul25.xlsx",
    "CLN1_Mutation": DATA_DIR / "cln1" / "cln01_mutation_table_jul25.xlsx",

    "CLN2_Patient": DATA_DIR / "cln2" / "cln02_patient_table_jan26.xlsx",
    "CLN2_Mutation": DATA_DIR / "cln2" / "cln02_mutation_table_jan26.xlsx",

    "CLN3_Patient": DATA_DIR / "cln3" / "cln03_patient_table_feb26.xlsx",
    "CLN3_Mutation": DATA_DIR / "cln3" / "cln03_mutation_table_feb26.xlsx",
}

for name, path in files.items():
    print(name, "→", path.exists())

CLN1_Patient → True
CLN1_Mutation → True
CLN2_Patient → True
CLN2_Mutation → True
CLN3_Patient → True
CLN3_Mutation → True

In [6]:
for name, file_path in files.items():

    print("\n" + "=" * 80)
    print("DATASET:", name)
    print("=" * 80)

    excel_file = pd.ExcelFile(file_path)

    print("Available Sheets:")
    print(excel_file.sheet_names)

================================================================================
DATASET: CLN1_Patient
================================================================================
Available Sheets:
['CLN1 Patient Database']

================================================================================
DATASET: CLN1_Mutation
================================================================================
Available Sheets:
['CLN1 mutation datasheet', 'Summary sheet']

================================================================================
DATASET: CLN2_Patient
================================================================================
Available Sheets:
['patients']

================================================================================
DATASET: CLN2_Mutation
================================================================================
Available Sheets:
['mutation data', 'Summary statistics', 'Affected residues', 'Other reports']

================================================================================
DATASET: CLN3_Patient
================================================================================
Available Sheets:
['Patient data', 'Sheet1']

================================================================================
DATASET: CLN3_Mutation
================================================================================
Available Sheets:
['mutation data ', 'Summary statistics', 'status uncertain']

In [8]:
# Define the correct worksheet for each dataset

sheets = {
    "CLN1_Patient": "CLN1 Patient Database",
    "CLN1_Mutation": "CLN1 mutation datasheet",

    "CLN2_Patient": "patients",
    "CLN2_Mutation": "mutation data",

    # We will confirm CLN3 Patient sheet automatically if needed
    "CLN3_Mutation": "mutation data "
}

In [9]:
def find_header_row(file_path, sheet_name, keywords, max_rows=30):

    raw_df = pd.read_excel(
        file_path,
        sheet_name=sheet_name,
        header=None,
        nrows=max_rows
    )

    for index, row in raw_df.iterrows():

        row_text = " ".join(
            str(value).lower()
            for value in row.values
            if pd.notna(value)
        )

        matches = sum(
            keyword.lower() in row_text
            for keyword in keywords
        )

        if matches >= 2:
            return index

    return None

In [10]:
cln1_patient_header = find_header_row(
    files["CLN1_Patient"],
    sheets["CLN1_Patient"],
    ["Patient ID", "Mutation", "Alleles", "Phenotype"]
)

print("CLN1 Patient Header Row:", cln1_patient_header)

CLN1 Patient Header Row: 9

In [11]:
cln1_mutation_header = find_header_row(
    files["CLN1_Mutation"],
    sheets["CLN1_Mutation"],
    ["Identifier", "Location", "Nucleotide change", "Amino acid"]
)

print("CLN1 Mutation Header Row:", cln1_mutation_header)

CLN1 Mutation Header Row: 8

In [12]:
cln1_patient = pd.read_excel(
    files["CLN1_Patient"],
    sheet_name=sheets["CLN1_Patient"],
    header=cln1_patient_header
)

cln1_mutation = pd.read_excel(
    files["CLN1_Mutation"],
    sheet_name=sheets["CLN1_Mutation"],
    header=cln1_mutation_header
)

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [13]:
print("=" * 70)
print("CLN1 PATIENT DATASET")
print("=" * 70)

print("\nShape:", cln1_patient.shape)

print("\nColumns:")
for i, column in enumerate(cln1_patient.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln1_patient.head())

======================================================================
CLN1 PATIENT DATASET
======================================================================

Shape: (535, 16)

Columns:
0: Patient ID
1: REL #
2: Patient ID2
3: Mutation #
4: Alleles
5: Changes in same gene
6: Changes in other genes
7: NCL Phenotype or other disease
8: Age at onset (y)
9: Histology
10: Country of origin
11: other ethnic detail
12: Country of Residence
13: Reference
14: PMID
15: Notes

First 5 rows:

,Patient ID,REL #,Patient ID2,Mutation #,Alleles,Changes in same gene,Changes in other genes,NCL Phenotype or other disease,Age at onset (y),Histology,Country of origin,other ethnic detail,Country of Residence,Reference,PMID,Notes
0,Pa-cln1.001,NaN,1_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect
1,Pa-cln1.001,NaN,1_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect
2,Pa-cln1.002,NaN,2_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect
3,Pa-cln1.002,NaN,2_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect
4,Pa-cln1.003,NaN,3_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,Finland,NaN,NaN,"Vesa et al., 1995",7637805,Finnish Founder effect

In [14]:
print("=" * 70)
print("CLN1 MUTATION DATASET")
print("=" * 70)

print("\nShape:", cln1_mutation.shape)

print("\nColumns:")
for i, column in enumerate(cln1_mutation.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln1_mutation.head())

======================================================================
CLN1 MUTATION DATASET
======================================================================

Shape: (111, 14)

Columns:
0: Identifier
1: Location
2: Nucleotide change
3: Amino acid change
4: Type of Mutation - DNA
5: Additional mutation information
6: Predicted functional effect
7: clinvar classification
8: rs number
9: contig position (GRCh38.p7)
10: PMID
11: References
12: Original description
13: Others notes

First 5 rows:

,Identifier,Location,Nucleotide change,Amino acid change,Type of Mutation - DNA,Additional mutation information,Predicted functional effect,clinvar classification,rs number,contig position (GRCh38.p7),PMID,References,Original description,Others notes
0,cln1.001,Exon 04,c.364A>T,p.(Arg122Trp),substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
1,cln1.002,Exon 02,c.163A>T,p.(Lys55*),substitution,nonsense,NaN,Likely pathogenic,rs386833633,40092469,7637805,Vesa et al. 1995,NaN,NaN
2,cln1.003,3'UTR,c.*526_*529del,p.(?),deletion,NaN,NaN,NaN,NaN,40073531,11589012,Mole et al. 2001,described as c.1451-1454del in paper.,NaN
3,cln1.004,Exon 02,c.223A>C,p.(Thr75Pro),substitution,Missense,Benign,Pathogenic,rs137852696,40092409,9425237,Mitchison et al. 1998,NaN,homozygous change in a number of patients
4,cln1.005,Exon 03,c.236A>G,p.(Asp79Gly),substitution,missense,Probably damaging,Pathogenic,rs137852697,40092171,9425237,Mitchison et al. 1998,NaN,NaN

In [15]:
print("Total rows:", len(cln1_patient))

print("\nExact duplicate rows:")
print(cln1_patient.duplicated().sum())

print("\nUnique Patient IDs:")
print(cln1_patient["Patient ID"].nunique())

print("\nMissing Patient IDs:")
print(cln1_patient["Patient ID"].isna().sum())

print("\nUnique Mutation IDs:")
print(cln1_patient["Mutation #"].nunique())

print("\nMissing Mutation IDs:")
print(cln1_patient["Mutation #"].isna().sum())

Total rows: 535

Exact duplicate rows:
150

Unique Patient IDs:
262

Missing Patient IDs:
15

Unique Mutation IDs:
96

Missing Mutation IDs:
47

In [16]:
patient_mutations = set(
    cln1_patient["Mutation #"]
    .dropna()
    .astype(str)
    .str.strip()
)

mutation_identifiers = set(
    cln1_mutation["Identifier"]
    .dropna()
    .astype(str)
    .str.strip()
)

matched_mutations = patient_mutations.intersection(
    mutation_identifiers
)

unmatched_patient_mutations = patient_mutations.difference(
    mutation_identifiers
)

print("Unique mutations in Patient Dataset:", len(patient_mutations))
print("Unique identifiers in Mutation Dataset:", len(mutation_identifiers))

print("\nMatched mutations:", len(matched_mutations))
print("Unmatched patient mutations:", len(unmatched_patient_mutations))

print("\nSample unmatched mutations:")
print(list(unmatched_patient_mutations)[:20])

Unique mutations in Patient Dataset: 95
Unique identifiers in Mutation Dataset: 102

Matched mutations: 95
Unmatched patient mutations: 0

Sample unmatched mutations:
[]

In [17]:
print("Total mutation rows:", len(cln1_mutation))

print("\nUnique Identifiers:")
print(cln1_mutation["Identifier"].nunique())

print("\nDuplicate Identifiers:")
print(
    cln1_mutation["Identifier"]
    .duplicated()
    .sum()
)

Total mutation rows: 111

Unique Identifiers:
102

Duplicate Identifiers:
8

In [18]:
duplicate_mutations = cln1_mutation[
    cln1_mutation["Identifier"].duplicated(keep=False)
].sort_values("Identifier")

print("Duplicate mutation records:")
display(duplicate_mutations)

Duplicate mutation records:

,Identifier,Location,Nucleotide change,Amino acid change,Type of Mutation - DNA,Additional mutation information,Predicted functional effect,clinvar classification,rs number,contig position (GRCh38.p7),PMID,References,Original description,Others notes
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
print(
    duplicate_mutations[
        ["Identifier"]
    ].value_counts()
)

Series([], Name: count, dtype: int64)

In [20]:
cln1_patient_clean = cln1_patient.drop_duplicates().copy()

print("Before removing exact duplicates:", len(cln1_patient))
print("After removing exact duplicates:", len(cln1_patient_clean))

print("\nExact duplicates remaining:")
print(cln1_patient_clean.duplicated().sum())

Before removing exact duplicates: 535
After removing exact duplicates: 385

Exact duplicates remaining:
0

In [21]:
print("Total rows:", len(cln1_mutation))

print("\nMissing Identifier values:")
print(cln1_mutation["Identifier"].isna().sum())

print("\nDuplicate Identifier values INCLUDING missing values:")
print(
    cln1_mutation["Identifier"]
    .duplicated()
    .sum()
)

print("\nNon-null Identifier duplicates:")
non_null_ids = cln1_mutation["Identifier"].dropna()

print(
    non_null_ids[
        non_null_ids.duplicated(keep=False)
    ].value_counts()
)

Total rows: 111

Missing Identifier values:
9

Duplicate Identifier values INCLUDING missing values:
8

Non-null Identifier duplicates:
Series([], Name: count, dtype: int64)

In [22]:
print("Completely empty rows:")
print(cln1_mutation.isna().all(axis=1).sum())

Completely empty rows:
9

In [23]:
cln1_mutation_clean = cln1_mutation.dropna(
    subset=["Identifier"]
).copy()

# Remove any accidental exact duplicates
cln1_mutation_clean = cln1_mutation_clean.drop_duplicates()

# Clean Identifier formatting
cln1_mutation_clean["Identifier"] = (
    cln1_mutation_clean["Identifier"]
    .astype(str)
    .str.strip()
)

print("Original mutation rows:", len(cln1_mutation))
print("Cleaned mutation rows:", len(cln1_mutation_clean))

print("\nMissing Identifiers:")
print(cln1_mutation_clean["Identifier"].isna().sum())

print("\nUnique Identifiers:")
print(cln1_mutation_clean["Identifier"].nunique())

print("\nDuplicate Identifiers:")
print(cln1_mutation_clean["Identifier"].duplicated().sum())

Original mutation rows: 111
Cleaned mutation rows: 102

Missing Identifiers:
0

Unique Identifiers:
102

Duplicate Identifiers:
0

In [24]:
cln1_patient_clean["Mutation #"] = (
    cln1_patient_clean["Mutation #"]
    .astype("string")
    .str.strip()
)

print("Missing Mutation IDs:")
print(cln1_patient_clean["Mutation #"].isna().sum())

print("\nUnique Mutation IDs:")
print(cln1_patient_clean["Mutation #"].nunique())

Missing Mutation IDs:
32

Unique Mutation IDs:
95

In [25]:
cln1_merged = cln1_patient_clean.merge(
    cln1_mutation_clean,
    how="left",
    left_on="Mutation #",
    right_on="Identifier",
    suffixes=("_patient", "_mutation")
)

print("Merged dataset shape:", cln1_merged.shape)

print("\nPatients with matched mutation information:")
print(cln1_merged["Identifier"].notna().sum())

print("\nPatients WITHOUT matched mutation information:")
print(cln1_merged["Identifier"].isna().sum())

Merged dataset shape: (385, 30)

Patients with matched mutation information:
353

Patients WITHOUT matched mutation information:
32

In [26]:
print("Merged Dataset Columns:\n")

for i, column in enumerate(cln1_merged.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln1_merged.head())

Merged Dataset Columns:

0: Patient ID
1: REL #
2: Patient ID2
3: Mutation #
4: Alleles
5: Changes in same gene
6: Changes in other genes
7: NCL Phenotype or other disease
8: Age at onset (y)
9: Histology
10: Country of origin
11: other ethnic detail
12: Country of Residence
13: Reference
14: PMID_patient
15: Notes
16: Identifier
17: Location
18: Nucleotide change
19: Amino acid change
20: Type of Mutation - DNA
21: Additional mutation information
22: Predicted functional effect
23: clinvar classification
24: rs number
25: contig position (GRCh38.p7)
26: PMID_mutation
27: References
28: Original description
29: Others notes

First 5 rows:

,Patient ID,REL #,Patient ID2,Mutation #,Alleles,Changes in same gene,Changes in other genes,NCL Phenotype or other disease,Age at onset (y),Histology,...,Type of Mutation - DNA,Additional mutation information,Predicted functional effect,clinvar classification,rs number,contig position (GRCh38.p7),PMID_mutation,References,Original description,Others notes
0,Pa-cln1.001,NaN,1_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,...,substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
1,Pa-cln1.002,NaN,2_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,...,substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
2,Pa-cln1.003,NaN,3_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,...,substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
3,Pa-cln1.004,NaN,4_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,...,substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...
4,Pa-cln1.005,NaN,5_Vesa_1995,cln1.001,p.Arg122Trp,NaN,NaN,infantile,NaN,NaN,...,substitution,missense,Probably damaging,Pathogenic,rs137852695,40091398,7637805,Vesa et al. 1995,NaN,Finnish major mutation. Mutation leads to intr...

In [27]:
cln1_merged["Disease_Subtype"] = "CLN1"

print(
    cln1_merged["Disease_Subtype"].value_counts()
)

Disease_Subtype
CLN1    385
Name: count, dtype: int64

In [28]:
print("=" * 60)
print("CLN1 DATASET FINAL SUMMARY")
print("=" * 60)

print("\nTotal Records:", len(cln1_merged))

print("\nUnique Patients:")
print(cln1_merged["Patient ID"].nunique())

print("\nRecords with Mutation Information:")
print(cln1_merged["Identifier"].notna().sum())

print("\nRecords without Mutation Information:")
print(cln1_merged["Identifier"].isna().sum())

print("\nDisease Subtype:")
print(cln1_merged["Disease_Subtype"].unique())

print("\nDataset Shape:")
print(cln1_merged.shape)

============================================================
CLN1 DATASET FINAL SUMMARY
============================================================

Total Records: 385

Unique Patients:
262

Records with Mutation Information:
353

Records without Mutation Information:
32

Disease Subtype:
<StringArray>
['CLN1']
Length: 1, dtype: str

Dataset Shape:
(385, 31)

In [29]:
missing_summary = (
    cln1_merged.isnull()
    .sum()
    .sort_values(ascending=False)
)

missing_summary = missing_summary[
    missing_summary > 0
]

print("Missing Values Per Column:\n")
print(missing_summary)

Missing Values Per Column:

Changes in other genes             384
Changes in same gene               383
other ethnic detail                362
Original description               361
REL #                              351
Country of Residence               298
Others notes                       269
Notes                              261
Histology                          250
Age at onset (y)                   217
Predicted functional effect        182
NCL Phenotype or other disease     129
rs number                           55
clinvar classification              54
Amino acid change                   52
Patient ID2                         51
PMID_mutation                       44
Type of Mutation - DNA              42
Country of origin                   40
Additional mutation information     33
Mutation #                          32
Nucleotide change                   32
Identifier                          32
Location                            32
contig position (GRCh38.p7)         32
References                          32
PMID_patient                        31
Reference                           11
Alleles                              5
Patient ID                           1
dtype: int64

In [30]:
from pathlib import Path

processed_path = Path("../data/processed")
processed_path.mkdir(
    parents=True,
    exist_ok=True
)

print("Processed data folder is ready!")

Processed data folder is ready!

In [31]:
cln1_merged.to_csv(
    processed_path / "cln1_processed.csv",
    index=False
)

print("CLN1 processed dataset saved successfully!")
print(
    "Location:",
    processed_path / "cln1_processed.csv"
)

CLN1 processed dataset saved successfully!
Location: ..\data\processed\cln1_processed.csv

In [32]:
cln2_patient_header = find_header_row(
    files["CLN2_Patient"],
    sheets["CLN2_Patient"],
    [
        "Patient ID",
        "Mutation",
        "Phenotype",
        "Age at onset"
    ]
)

print("CLN2 Patient Header Row:", cln2_patient_header)

CLN2 Patient Header Row: 13

In [33]:
cln2_mutation_header = find_header_row(
    files["CLN2_Mutation"],
    sheets["CLN2_Mutation"],
    [
        "Identifier",
        "Location",
        "Nucleotide change",
        "Amino acid"
    ]
)

print("CLN2 Mutation Header Row:", cln2_mutation_header)

CLN2 Mutation Header Row: 18

In [34]:
cln2_patient = pd.read_excel(
    files["CLN2_Patient"],
    sheet_name=sheets["CLN2_Patient"],
    header=cln2_patient_header
)

cln2_mutation = pd.read_excel(
    files["CLN2_Mutation"],
    sheet_name=sheets["CLN2_Mutation"],
    header=cln2_mutation_header
)

print("CLN2 datasets loaded successfully!")

CLN2 datasets loaded successfully!

In [35]:
print("=" * 70)
print("CLN2 PATIENT DATASET")
print("=" * 70)

print("\nShape:", cln2_patient.shape)

print("\nColumns:")
for i, column in enumerate(cln2_patient.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln2_patient.head())

======================================================================
CLN2 PATIENT DATASET
======================================================================

Shape: (1171, 20)

Columns:
0: Patient identifer
1: REL#
2: Other Patient ID
3: mutation number
4: Allele
5: Changes in the same gene
6: Changes in other genes
7: NCL Phenotype or other disease
8: Age of onset (y)
9: Histology
10: Country of origin
11: other ethnic detail
12: Country of residence
13: Reference
14: PMID
15: Notes
16: Notes2
17: Notes3
18: Notes4
19: Notes5

First 5 rows:

,Patient identifer,REL#,Other Patient ID,mutation number,Allele,Changes in the same gene,Changes in other genes,NCL Phenotype or other disease,Age of onset (y),Histology,Country of origin,other ethnic detail,Country of residence,Reference,PMID,Notes,Notes2,Notes3,Notes4,Notes5
0,Pa-cln2.001,NaN,C7787_Sleat_1997,cln2.004,c.509-1G>C,NaN,NaN,late infantile,NaN,NaN,Ireland / Scotland / England,NaN,NaN,"Sleat et al., 1997",9295267,NaN,NaN,NaN,NaN,NaN
1,Pa-cln2.001,NaN,C7787_Sleat_1997,cln2.001,p.(Arg208*),NaN,NaN,late infantile,NaN,NaN,Ireland / Scotland / England,NaN,NaN,"Sleat et al., 1997",9295267,NaN,NaN,NaN,NaN,NaN
2,Pa-cln2.002,NaN,1_Zhong_1998,cln2.004,c.509-1G>C,NaN,NaN,late infantile,NaN,NaN,USA,NaN,NaN,"Wisniewski et al., 1998",9492089,NaN,NaN,NaN,NaN,NaN
3,Pa-cln2.002,NaN,1_Zhong_1998,cln2.004,c.509-1G>C,NaN,NaN,late infantile,NaN,NaN,USA,NaN,NaN,"Wisniewski et al., 1998",9492089,NaN,NaN,NaN,NaN,NaN
4,Pa-cln2.003,NaN,2_Zhong_1998,cln2.004,c.509-1G>C,NaN,NaN,late infantile,NaN,NaN,USA,NaN,NaN,"Wisniewski et al., 1999",9492089,NaN,NaN,NaN,NaN,NaN

In [36]:
print("=" * 70)
print("CLN2 MUTATION DATASET")
print("=" * 70)

print("\nShape:", cln2_mutation.shape)

print("\nColumns:")
for i, column in enumerate(cln2_mutation.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln2_mutation.head())

======================================================================
CLN2 MUTATION DATASET
======================================================================

Shape: (187, 16)

Columns:
0: Identifier
1: Location
2: Nucleotide change
3: Amino acid change
4: Type of Mutation - DNA
5: additional mutation info
6: Predicted functional effect in silico
7: Splice AI scores
8: clinvar classification
9: rs number
10: contig position (GRCh38.p7)
11: Reference
12: PMID
13: Original description
14: Notes
15: Notes 2

First 5 rows:

,Identifier,Location,Nucleotide change,Amino acid change,Type of Mutation - DNA,additional mutation info,Predicted functional effect in silico,Splice AI scores,clinvar classification,rs number,contig position (GRCh38.p7),Reference,PMID,Original description,Notes,Notes 2
0,cln2.001,Exon 06,c.622C>T,p.(Arg208*),substitution,Nonsense,NaN,NaN,pathogenic,rs119455955,6617040G>A,Sleat et al. 1999,10330339,NaN,NaN,NaN
1,cln2.002,Exon 09,c.1093T>C,p.(Cys365Arg),substitution,Missense,Probably damaging,NaN,pathogenic,rs119455953,6616057A>G,Sleat et al. 1999,10330339,NaN,NaN,NaN
2,cln2.003,Exon 09,c.1094G>A,p.(Cys365Tyr),substitution,Missense,Probably damaging,NaN,pathogenic/likely pathogenic,rs119455953,6616057C>T,Sleat et al. 1999,10330339,NaN,NaN,NaN
3,cln2.004,Intron 05,c.509-1G>C,NaN,substitution,splice acceptor variant,NaN,Acceptor loss 0.96,pathogenic,rs56144125,6617154C>G,Sleat et al. 1999,10330339,g.3556G>C,Described as p.(Phe169*) (Sleat) and p.(Val170...,NaN
4,cln2.005,Exon 05,c.481C>T,p.(Gln161*),substitution,Nonsense,NaN,NaN,NaN,NaN,6617328G>A,"pers comm Raymond Wang, USA",NaN,NaN,This number was previously used for a differe...,NaN

In [37]:
print("=" * 60)
print("CLN2 PATIENT DATA ANALYSIS")
print("=" * 60)

print("\nTotal rows:", len(cln2_patient))

print("\nExact duplicate rows:")
print(cln2_patient.duplicated().sum())

print("\nUnique Patient Identifiers:")
print(cln2_patient["Patient identifer"].nunique())

print("\nMissing Patient Identifiers:")
print(cln2_patient["Patient identifer"].isna().sum())

print("\nUnique Mutation Numbers:")
print(cln2_patient["mutation number"].nunique())

print("\nMissing Mutation Numbers:")
print(cln2_patient["mutation number"].isna().sum())

============================================================
CLN2 PATIENT DATA ANALYSIS
============================================================

Total rows: 1171

Exact duplicate rows:
247

Unique Patient Identifiers:
583

Missing Patient Identifiers:
10

Unique Mutation Numbers:
190

Missing Mutation Numbers:
87

In [38]:
print("=" * 60)
print("CLN2 MUTATION DATA ANALYSIS")
print("=" * 60)

print("\nTotal rows:", len(cln2_mutation))

print("\nMissing Identifiers:")
print(cln2_mutation["Identifier"].isna().sum())

print("\nUnique Identifiers:")
print(cln2_mutation["Identifier"].nunique())

print("\nDuplicate Identifiers INCLUDING NaN:")
print(cln2_mutation["Identifier"].duplicated().sum())

# Check genuine duplicates excluding missing values
non_null_ids = cln2_mutation["Identifier"].dropna()

print("\nNon-null Identifier duplicates:")
print(
    non_null_ids[
        non_null_ids.duplicated(keep=False)
    ].value_counts()
)

============================================================
CLN2 MUTATION DATA ANALYSIS
============================================================

Total rows: 187

Missing Identifiers:
0

Unique Identifiers:
186

Duplicate Identifiers INCLUDING NaN:
1

Non-null Identifier duplicates:
Identifier
cln2.144    2
Name: count, dtype: int64

In [39]:
patient_mutations_cln2 = set(
    cln2_patient["mutation number"]
    .dropna()
    .astype(str)
    .str.strip()
)

mutation_identifiers_cln2 = set(
    cln2_mutation["Identifier"]
    .dropna()
    .astype(str)
    .str.strip()
)

matched_mutations_cln2 = (
    patient_mutations_cln2.intersection(
        mutation_identifiers_cln2
    )
)

unmatched_patient_mutations_cln2 = (
    patient_mutations_cln2.difference(
        mutation_identifiers_cln2
    )
)

print("Unique mutations in Patient Dataset:",
      len(patient_mutations_cln2))

print("Unique identifiers in Mutation Dataset:",
      len(mutation_identifiers_cln2))

print("\nMatched mutations:",
      len(matched_mutations_cln2))

print("Unmatched patient mutations:",
      len(unmatched_patient_mutations_cln2))

print("\nSample unmatched mutations:")
print(list(unmatched_patient_mutations_cln2)[:20])

Unique mutations in Patient Dataset: 190
Unique identifiers in Mutation Dataset: 186

Matched mutations: 185
Unmatched patient mutations: 5

Sample unmatched mutations:
['cln2.070', 'novel', 'wild type', 'cln2.139 ; cln2.097', 'in analysis']

In [40]:
cln2_patient_clean = cln2_patient.drop_duplicates().copy()

print("Before removing exact duplicates:", len(cln2_patient))
print("After removing exact duplicates:", len(cln2_patient_clean))
print("Exact duplicates remaining:", cln2_patient_clean.duplicated().sum())

Before removing exact duplicates: 1171
After removing exact duplicates: 924
Exact duplicates remaining: 0

In [41]:
cln2_144 = cln2_mutation[
    cln2_mutation["Identifier"]
    .astype(str)
    .str.strip()
    .eq("cln2.144")
]

display(cln2_144)

,Identifier,Location,Nucleotide change,Amino acid change,Type of Mutation - DNA,additional mutation info,Predicted functional effect in silico,Splice AI scores,clinvar classification,rs number,contig position (GRCh38.p7),Reference,PMID,Original description,Notes,Notes 2
139,cln2.144,Exon 03,c.163C>T,p.(Gln55*),substitution,Nonsense,NaN,NaN,NaN,NaN,6618842,Corina-Marcela Rus report to LOVD,NaN,NaN,NaN,NaN
140,cln2.144,Exon 10,c.1226G>T,p.(Gly409Val),substitution,missense,Probably damaging,NaN,NaN,NaN,6615482C>A,"pers comm Carrie Fagerstrom, 2015",NaN,NaN,NaN,NaN

In [42]:
print("Are the two cln2.144 rows completely identical?")
print(cln2_144.duplicated().sum())

Are the two cln2.144 rows completely identical?
0

In [43]:
print("Searching for cln2.070 in mutation dataset:\n")

display(
    cln2_mutation[
        cln2_mutation.astype(str)
        .apply(
            lambda row: row.str.contains(
                "cln2.070",
                case=False,
                na=False
            ).any(),
            axis=1
        )
    ]
)

Searching for cln2.070 in mutation dataset:

Empty DataFrame
Columns: [Identifier, Location, Nucleotide change, Amino acid change, Type of Mutation - DNA, additional mutation info, Predicted functional effect in silico, Splice AI scores, clinvar classification, rs number, contig position (GRCh38.p7), Reference, PMID, Original description, Notes, Notes 2]
Index: []

In [44]:
special_values = [
    "novel",
    "wild type",
    "in analysis",
    "cln2.139 ; cln2.097",
    "cln2.070"
]

special_records = cln2_patient_clean[
    cln2_patient_clean["mutation number"]
    .astype(str)
    .str.strip()
    .isin(special_values)
]

print("Number of records with special/unmatched mutation values:")
print(len(special_records))

display(
    special_records[
        [
            "Patient identifer",
            "mutation number",
            "Allele",
            "NCL Phenotype or other disease",
            "Age of onset (y)"
        ]
    ].head(20)
)

Number of records with special/unmatched mutation values:
9

,Patient identifer,mutation number,Allele,NCL Phenotype or other disease,Age of onset (y)
793,Pa-cln2.400,wild type,wild type,infantile,1
797,Pa-cln2.402,in analysis,NaN,late infantile,3
831,Pa-cln2.419,in analysis,NaN,juvenile,8
834,Pa-cln2.421,cln2.139 ; cln2.097,p.(Arg350Trp) ; p.(Val480Met),juvenile,9
860,Pa-cln2.434,cln2.070,p.(Gln55*),late infantile,2.5
1029,Pa-cln2.518,novel,p.(Tyr406*),late infantile,2.4
1107,Pa-cln2.557,novel,p.(Tyr406*),late infantile,2.4
1111,Pa-cln2.559,novel,p.(Tyr449Asn),juvenile,6
1123,Pa-cln2.565,novel,p.(Tyr449Asn),juvenile,7

In [45]:
# Create a copy
cln2_mutation_clean = cln2_mutation.copy()

# Remove completely empty rows
cln2_mutation_clean = cln2_mutation_clean.dropna(how="all")

# Remove rows where Identifier is missing
cln2_mutation_clean = cln2_mutation_clean.dropna(
    subset=["Identifier"]
)

# Clean Identifier text
cln2_mutation_clean["Identifier"] = (
    cln2_mutation_clean["Identifier"]
    .astype(str)
    .str.strip()
)

print("Original mutation rows:", len(cln2_mutation))
print("Cleaned mutation rows:", len(cln2_mutation_clean))

print("\nMissing Identifiers:")
print(cln2_mutation_clean["Identifier"].isna().sum())

print("\nDuplicate Identifier values:")
print(
    cln2_mutation_clean["Identifier"]
    .value_counts()
    .loc[lambda x: x > 1]
)

Original mutation rows: 187
Cleaned mutation rows: 187

Missing Identifiers:
0

Duplicate Identifier values:
Identifier
cln2.144    2
Name: count, dtype: int64

In [46]:
# Create a merge-safe mutation lookup table

cln2_mutation_lookup = (
    cln2_mutation_clean
    .drop_duplicates(
        subset=["Identifier"],
        keep="first"
    )
    .copy()
)

print("Original cleaned mutation records:")
print(len(cln2_mutation_clean))

print("\nMerge-safe mutation records:")
print(len(cln2_mutation_lookup))

print("\nUnique Identifiers:")
print(
    cln2_mutation_lookup["Identifier"]
    .nunique()
)

print("\nDuplicate Identifiers remaining:")
print(
    cln2_mutation_lookup["Identifier"]
    .duplicated()
    .sum()
)

Original cleaned mutation records:
187

Merge-safe mutation records:
186

Unique Identifiers:
186

Duplicate Identifiers remaining:
0

In [47]:
cln2_patient_clean["mutation number"] = (
    cln2_patient_clean["mutation number"]
    .astype("string")
    .str.strip()
)

print("Unique mutation values:")
print(
    cln2_patient_clean["mutation number"]
    .nunique()
)

print("\nMissing mutation values:")
print(
    cln2_patient_clean["mutation number"]
    .isna()
    .sum()
)

Unique mutation values:
190

Missing mutation values:
72

In [48]:
cln2_patient_merge = cln2_patient_clean.rename(
    columns={
        "mutation number": "Mutation_ID"
    }
).copy()

cln2_mutation_merge = cln2_mutation_lookup.rename(
    columns={
        "Identifier": "Mutation_ID"
    }
).copy()

In [49]:
cln2_merged = cln2_patient_merge.merge(
    cln2_mutation_merge,
    on="Mutation_ID",
    how="left",
    suffixes=(
        "_patient",
        "_mutation"
    )
)

print("Patient records before merge:")
print(len(cln2_patient_merge))

print("\nRecords after merge:")
print(len(cln2_merged))

print("\nMerged dataset shape:")
print(cln2_merged.shape)

Patient records before merge:
924

Records after merge:
924

Merged dataset shape:
(924, 35)

In [50]:
print("Total patient records:")
print(len(cln2_merged))

print("\nPatients with mutation information:")
print(
    cln2_merged["Nucleotide change"]
    .notna()
    .sum()
)

print("\nPatients WITHOUT matched mutation information:")
print(
    cln2_merged["Nucleotide change"]
    .isna()
    .sum()
)

Total patient records:
924

Patients with mutation information:
842

Patients WITHOUT matched mutation information:
82

In [51]:
cln2_merged["Disease_Subtype"] = "CLN2"

print(
    cln2_merged["Disease_Subtype"]
    .unique()
)

<StringArray>
['CLN2']
Length: 1, dtype: str

In [52]:
print("=" * 60)
print("CLN2 DATASET FINAL SUMMARY")
print("=" * 60)

print("\nTotal Records:")
print(len(cln2_merged))

print("\nUnique Patients:")
print(
    cln2_merged["Patient identifer"]
    .nunique()
)

print("\nRecords with Mutation Information:")
print(
    cln2_merged["Nucleotide change"]
    .notna()
    .sum()
)

print("\nRecords without Mutation Information:")
print(
    cln2_merged["Nucleotide change"]
    .isna()
    .sum()
)

print("\nDisease Subtype:")
print(
    cln2_merged["Disease_Subtype"]
    .unique()
)

print("\nDataset Shape:")
print(
    cln2_merged.shape
)

============================================================
CLN2 DATASET FINAL SUMMARY
============================================================

Total Records:
924

Unique Patients:
583

Records with Mutation Information:
842

Records without Mutation Information:
82

Disease Subtype:
<StringArray>
['CLN2']
Length: 1, dtype: str

Dataset Shape:
(924, 36)

In [53]:
from pathlib import Path

processed_path = Path("../data/processed")

processed_path.mkdir(
    parents=True,
    exist_ok=True
)

cln2_merged.to_csv(
    processed_path / "cln2_processed.csv",
    index=False
)

print("CLN2 processed dataset saved successfully!")
print(
    "Location:",
    processed_path / "cln2_processed.csv"
)

CLN2 processed dataset saved successfully!
Location: ..\data\processed\cln2_processed.csv

In [54]:
import pandas as pd
import numpy as np
from pathlib import Path

cln3_patient_path = "../data/raw/cln3/cln03_patient_table_feb26.xlsx"
cln3_mutation_path = "../data/raw/cln3/cln03_mutation_table_feb26.xlsx"

print("Paths ready!")

Paths ready!

In [57]:
def find_header_row(file_path, sheet_name=0, search_text="Patient"):
    
    temp = pd.read_excel(
        file_path,
        sheet_name=sheet_name,
        header=None
    )

    for index, row in temp.iterrows():

        # Convert every value safely into a string
        row_text = " ".join(
            str(value) for value in row.tolist()
        ).lower()

        if search_text.lower() in row_text:
            return index

    return None


# Find CLN3 Patient Header
cln3_patient_header = find_header_row(
    cln3_patient_path,
    search_text="Patient"
)


# Find CLN3 Mutation Header
cln3_mutation_header = find_header_row(
    cln3_mutation_path,
    search_text="Identifier"
)


print("CLN3 Patient Header:", cln3_patient_header)
print("CLN3 Mutation Header:", cln3_mutation_header)

CLN3 Patient Header: 6
CLN3 Mutation Header: 11

In [58]:
import pandas as pd

# ============================================================
# LOAD CLN3 PATIENT DATASET
# ============================================================

cln3_patient = pd.read_excel(
    cln3_patient_path,
    header=cln3_patient_header
)

# Remove completely empty rows
cln3_patient = cln3_patient.dropna(how="all")

# Clean column names
cln3_patient.columns = (
    cln3_patient.columns
    .astype(str)
    .str.strip()
)


# ============================================================
# LOAD CLN3 MUTATION DATASET
# ============================================================

cln3_mutation = pd.read_excel(
    cln3_mutation_path,
    header=cln3_mutation_header
)

# Remove completely empty rows
cln3_mutation = cln3_mutation.dropna(how="all")

# Clean column names
cln3_mutation.columns = (
    cln3_mutation.columns
    .astype(str)
    .str.strip()
)


# ============================================================
# DISPLAY RESULTS
# ============================================================

print("=" * 70)
print("CLN3 PATIENT DATASET")
print("=" * 70)

print("Shape:", cln3_patient.shape)
print("\nColumns:")
for i, column in enumerate(cln3_patient.columns):
    print(i, ":", repr(column))


print("\nFirst 5 rows:")
display(cln3_patient.head())


print("\n" + "=" * 70)
print("CLN3 MUTATION DATASET")
print("=" * 70)

print("Shape:", cln3_mutation.shape)
print("\nColumns:")
for i, column in enumerate(cln3_mutation.columns):
    print(i, ":", repr(column))


print("\nFirst 5 rows:")
display(cln3_mutation.head())

======================================================================
CLN3 PATIENT DATASET
======================================================================
Shape: (609, 17)

Columns:
0 : 'No. patients'
1 : '298'
2 : 'Unnamed: 2'
3 : 'Unnamed: 3'
4 : 'Unnamed: 4'
5 : 'Unnamed: 5'
6 : 'Unnamed: 6'
7 : 'Unnamed: 7'
8 : 'Unnamed: 8'
9 : 'Unnamed: 9'
10 : 'Unnamed: 10'
11 : 'Unnamed: 11'
12 : 'Unnamed: 12'
13 : 'Unnamed: 13'
14 : 'Unnamed: 14'
15 : 'Unnamed: 15'
16 : 'Unnamed: 16'

First 5 rows:

,No. patients,298,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,No. families,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Additional notes,Note that the exons/introns are numbered accor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,c.1211 variant previously numbered as cln3.028...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,"There are probably errors in this table, parti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Updated Feb26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
CLN3 MUTATION DATASET
======================================================================
Shape: (138, 18)

Columns:
0 : 'Identifier'
1 : 'Location'
2 : 'Nucleotide change'
3 : 'Amino acid position'
4 : 'Amino acid change'
5 : 'Type of Mutation - DNA'
6 : 'additional mutation info'
7 : 'Predicted functional effect in silico'
8 : 'Predicted effect on splicing - exonic variants'
9 : 'clinvar classification'
10 : 'rs number'
11 : 'GRCh38'
12 : 'Reference'
13 : 'PMID'
14 : 'Original description'
15 : 'Other notes'
16 : 'hgmd reference'
17 : 'Column1'

First 5 rows:

,Identifier,Location,Nucleotide change,Amino acid position,Amino acid change,Type of Mutation - DNA,additional mutation info,Predicted functional effect in silico,Predicted effect on splicing - exonic variants,clinvar classification,rs number,GRCh38,Reference,PMID,Original description,Other notes,hgmd reference,Column1
0,cln3.001,Intron 07 - 09,c.461-280_677+382del,NaN,p.(?),deletion,complex,see notes,NaN,Pathogenic,rs1555468634,g.28485965_28486930del,"The International Batten Disease Consortium, 1...",7553855,NaN,This deletion mutation was originally believed...,NaN,NaN
1,cln3.002,Intron 10 - 14,c.(790+1_791-1)_(1056+1_1057-1)del,NaN,p.(Gly264Valfs*29),deletion,uncertain,see notes,NaN,Pathogenic,NaN,NaN,"Munroe et al., Am J Hum Genet; 1997",9311735,2.8 kb deletion or p.(Gly264_Gln352delinsValfs...,Amino acid change taken from ClinVar entry; no...,NaN,NaN
2,cln3.003,Exon 07 - 16,c.432_*33del,NaN,p.(?),deletion,deletion,see notes,NaN,NaN,NaN,g.28477483_28487484del,"Mitchison et al., Am J Hum Genet, 1995",7887419,c.432+?_1350-?del; 28488804_28498805del. Minim...,deletion of 6 kb that starts between F2 and F4...,CG952289,NaN
3,cln3.004,Intron 08,c.533+1G>C,NaN,p.(?),substitution,splice donor variant,most probably affecting splicing,NaN,likely pathogenic,rs386833728,g.28486577C>G,"Munroe et al., Am J Hum Genet; 1997",9311735,NaN,670+1G>C; c.533+1G>C splice defect,NaN,NaN
4,cln3.005,Exon 06,c.302T>C,101,p.(Leu101Pro),substitution,missense,Probably damaging,no significant impact on splicing signals,likely pathogenic,rs386833714,g.28487734A>G,"Munroe et al., Am J Hum Genet; 1997",9311735,NaN,NaN,CM970329,NaN

In [59]:
print("\nCLN3 PATIENT COLUMNS:")
print("-" * 50)

for i, column in enumerate(cln3_patient.columns):
    print(f"{i}: '{column}'")


print("\n\nCLN3 MUTATION COLUMNS:")
print("-" * 50)

for i, column in enumerate(cln3_mutation.columns):
    print(f"{i}: '{column}'")

CLN3 PATIENT COLUMNS:
--------------------------------------------------
0: 'No. patients'
1: '298'
2: 'Unnamed: 2'
3: 'Unnamed: 3'
4: 'Unnamed: 4'
5: 'Unnamed: 5'
6: 'Unnamed: 6'
7: 'Unnamed: 7'
8: 'Unnamed: 8'
9: 'Unnamed: 9'
10: 'Unnamed: 10'
11: 'Unnamed: 11'
12: 'Unnamed: 12'
13: 'Unnamed: 13'
14: 'Unnamed: 14'
15: 'Unnamed: 15'
16: 'Unnamed: 16'


CLN3 MUTATION COLUMNS:
--------------------------------------------------
0: 'Identifier'
1: 'Location'
2: 'Nucleotide change'
3: 'Amino acid position'
4: 'Amino acid change'
5: 'Type of Mutation - DNA'
6: 'additional mutation info'
7: 'Predicted functional effect in silico'
8: 'Predicted effect on splicing - exonic variants'
9: 'clinvar classification'
10: 'rs number'
11: 'GRCh38'
12: 'Reference'
13: 'PMID'
14: 'Original description'
15: 'Other notes'
16: 'hgmd reference'
17: 'Column1'

In [60]:
import pandas as pd

# Read CLN3 patient file WITHOUT assigning a header
temp_cln3 = pd.read_excel(
    cln3_patient_path,
    header=None
)

# Search every row for important patient-related keywords
for index, row in temp_cln3.iterrows():

    row_text = " ".join(
        str(value) for value in row.tolist()
    ).lower()

    if (
        "patient id" in row_text
        or "patient identifier" in row_text
        or "mutation" in row_text
    ):
        print("\n" + "=" * 80)
        print("POSSIBLE HEADER ROW:", index)
        print("=" * 80)
        print(row.tolist())

================================================================================
POSSIBLE HEADER ROW: 9
================================================================================
['Additional notes', 'Note that the exons/introns are numbered according to the most reference sequence, in which exon 1 is not transcribed. The classic CLN3 mutation is generally referred to in the literature as deletion of (transcribed) exons 7 and 8.', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

================================================================================
POSSIBLE HEADER ROW: 14
================================================================================
['DB Patient ID', 'REL#', 'Other Patient ID', 'mutation number', 'allele', 'Changes in same gene', 'Changes in other genes', 'NCL phenotype or other disease', 'Age at onset (y)', 'Histology', 'Country of origin', 'Other ethnic detail', 'Country of residence', 'Reference', 'PMID', 'Notes', 'Notes2']

================================================================================
POSSIBLE HEADER ROW: 16
================================================================================
['Pa-cln3.140', nan, 'L199Pa 7_Lauronen_1999', 'cln3.002', 'c.(790+1_791-1)_(1056+1_1057-1)del', nan, nan, 'Protracted juvenile', 5.5, 'FP / CL', 'Finland', nan, nan, 'Munroe et al., 1997', 9151312, 'PMID updated June 2025, as wrong paper selected', 'Kousi 2012 says breakpoints not determined. c.791-802_1056+1445del previously entered in this datasheet. Query whether ClinVar record with updated coordinates is the same mutation. D16S28 is NOT deleted; thus different mutation to cln3.027']

================================================================================
POSSIBLE HEADER ROW: 347
================================================================================
['Pa-cln3.404', nan, nan, 'cln3.001', 'c.461-280_677+382del', nan, nan, 'severe 16p deletion syndrome', 9, nan, 'France', nan, nan, 'Pebrel-Richard et al., 2014', 23860047, 'hemizygous 16p11.2 microdeletion unmasks 1kb mutation in CLN3', nan]

================================================================================
POSSIBLE HEADER ROW: 348
================================================================================
['Pa-cln3.404', nan, 'Pebrel-Richard_2014', 'cln3.069', '1.7 Mb microdeletion', nan, nan, 'severe 16p deletion syndrome', 9, nan, 'France', nan, nan, 'Pebrel-Richard et al., 2014', 23860047, 'hemizygous 16p11.2 microdeletion unmasks 1kb mutation in CLN3', nan]

================================================================================
POSSIBLE HEADER ROW: 463
================================================================================
['Pa-cln3.462', nan, nan, 'cln3.099', 'c.461-24_677+27del', nan, 'mutation in BEST1 ', 'visual loss', 7.75, nan, nan, nan, 'Spain', 'pers comm from relative', nan, 'No details of BEST1 mutation; mother reports her mutation as Ser335Tyr, although this would mean c.1004C>A was change, or something other than a point mutation.', 'cone dystrophy; foveal hypoplasia and bilateral maculopathy']

================================================================================
POSSIBLE HEADER ROW: 464
================================================================================
['Pa-cln3.462', nan, nan, 'cln3.100', 'p.(Ser335Pro)', nan, 'mutation in BEST1', 'visual loss', 7.75, nan, nan, nan, 'Spain', 'pers comm from relative', nan, 'No details of BEST1 mutation; mother reports her mutation as Ser335Tyr, although this would mean c.1004C>A was change, or something other than a point mutation.', 'cone dystrophy; foveal hypoplasia and bilateral maculopathy']

================================================================================
POSSIBLE HEADER ROW: 481
================================================================================
['Pa-cln3.471', nan, 623, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 482
================================================================================
['Pa-cln3.471', nan, 623, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 483
================================================================================
['Pa-cln3.472', nan, 624, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 484
================================================================================
['Pa-cln3.472', nan, 624, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 485
================================================================================
['Pa-cln3.473', nan, 625, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 486
================================================================================
['Pa-cln3.473', nan, 625, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 487
================================================================================
['Pa-cln3.474', nan, 626, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 488
================================================================================
['Pa-cln3.474', nan, 626, 'cln3.113', 'p.(Leu102del)', nan, nan, 'IRD', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 489
================================================================================
['Pa-cln3.475', nan, 10, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'RP', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 490
================================================================================
['Pa-cln3.475', nan, 10, 'cln3.074', 'p.(Arg405Trp)', nan, nan, 'RP', nan, nan, nan, nan, nan, 'Stone et al. 2018', 28559085, 'panel of 1000 IRD patients - 5 with CLN3 mutations. No further clinical details', nan]

================================================================================
POSSIBLE HEADER ROW: 509
================================================================================
['Pa-cln3.485', nan, nan, 'cln3.001', 'с.461-280_677+382del', nan, nan, 'bilateral chorioretinal scarring', nan, nan, nan, nan, nan, 'Honasoge and Smith, 2022', 35599949, 'Diabetic patient, presented at age 63; probable heterozygous effect of classic mutation', nan]

================================================================================
POSSIBLE HEADER ROW: 510
================================================================================
['Pa-cln3.485', nan, nan, 'wildtype', nan, nan, nan, 'bilateral chorioretinal scarring', nan, nan, nan, nan, nan, 'Honasoge and Smith, 2022', 35599949, 'Diabetic patient, presented at age 63; probable heterozygous effect of classic mutation', nan]

================================================================================
POSSIBLE HEADER ROW: 517
================================================================================
['Pa-cln3.489', nan, 'RKK-79', 'cln3.001', 'с.461-280_677+382del', nan, nan, 'RP', 66, nan, nan, nan, nan, 'Wen et al. 2023', 36811936, 'Mutation described as c.461-279_677+384del; is  more than likely cln3.001', nan]

================================================================================
POSSIBLE HEADER ROW: 553
================================================================================
['Pa-cln3.515', nan, nan, 'cln3.001', 'c.461-280_677+382del', nan, nan, 'Adult', 63, nan, nan, nan, nan, 'Honasoge and Smith 2022', 'PMC9121241', 'Mild nuclear sclerosis, numerous pigmented chorioretinal scars, tracking into macula. From the description of the mutation, it is probably the 1kb deletion, but described incorrectly wrt to current reference sequences.', nan]

================================================================================
POSSIBLE HEADER ROW: 554
================================================================================
['Pa-cln3.515', nan, nan, nan, 'wildtype', nan, nan, 'Adult', 63, nan, nan, nan, nan, 'Honasoge and Smith 2022', 'PMC9121241', 'Mild nuclear sclerosis, numerous pigmented chorioretinal scars, tracking into macula. From the description of the mutation, it is probably the 1kb deletion, but described incorrectly wrt to current reference sequences.', nan]

================================================================================
POSSIBLE HEADER ROW: 561
================================================================================
['Pa-cln3.519', nan, 'ucl-pax_6', 'cln3.127', nan, nan, nan, 'juvenile', 5, nan, 'Germany', nan, nan, 'Minnis et al. 2025', nan, 'visual loss, cognitive/language/motor decline, behavioural and psychiatric abnormalities', 'The coordinates of the deletion in this patient cannot be validated. See mutation datasheet for full details. Preprint: https://doi.org/10.1101/2025.04.24.650398']

================================================================================
POSSIBLE HEADER ROW: 597
================================================================================
['Pa-cln3.537', nan, '0,191,773', 'cln3.139', 'p.(Gly280Cys)', nan, nan, 'juvenile', 6, nan, 'China', nan, nan, 'Zhang et al. 2024', 39563673, 'Onset with night blindness, rapid vision loss; displayed typical CLN3 phenotype', 'Query about the location of this mutation - see mutation table']

================================================================================
POSSIBLE HEADER ROW: 621
================================================================================
['Further study is needed to more precisely determine the disease phenotypes displayed by patients with homozygous mutations in CLN3', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

In [61]:
# Change 10 to the row number shown in your output

header_candidate = 10

display(
    temp_cln3.iloc[
        header_candidate - 3 : header_candidate + 5
    ]
)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
7,No. families,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Additional notes,Note that the exons/introns are numbered accor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,c.1211 variant previously numbered as cln3.028...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,"There are probably errors in this table, parti...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Updated Feb26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DB Patient ID,REL#,Other Patient ID,mutation number,allele,Changes in same gene,Changes in other genes,NCL phenotype or other disease,Age at onset (y),Histology,Country of origin,Other ethnic detail,Country of residence,Reference,PMID,Notes,Notes2

In [62]:
# ============================================================
# RELOAD CLN3 PATIENT DATASET WITH CORRECT HEADER
# ============================================================

cln3_patient = pd.read_excel(
    cln3_patient_path,
    header=14
)

# Remove completely empty rows
cln3_patient = cln3_patient.dropna(how="all")

# Clean column names
cln3_patient.columns = (
    cln3_patient.columns
    .astype(str)
    .str.strip()
)

print("=" * 70)
print("CLN3 PATIENT DATASET")
print("=" * 70)

print("\nShape:", cln3_patient.shape)

print("\nColumns:")
for i, column in enumerate(cln3_patient.columns):
    print(f"{i}: {column}")

print("\nFirst 5 rows:")
display(cln3_patient.head())

======================================================================
CLN3 PATIENT DATASET
======================================================================

Shape: (603, 17)

Columns:
0: DB Patient ID
1: REL#
2: Other Patient ID
3: mutation number
4: allele
5: Changes in same gene
6: Changes in other genes
7: NCL phenotype or other disease
8: Age at onset (y)
9: Histology
10: Country of origin
11: Other ethnic detail
12: Country of residence
13: Reference
14: PMID
15: Notes
16: Notes2

First 5 rows:

,DB Patient ID,REL#,Other Patient ID,mutation number,allele,Changes in same gene,Changes in other genes,NCL phenotype or other disease,Age at onset (y),Histology,Country of origin,Other ethnic detail,Country of residence,Reference,PMID,Notes,Notes2
0,Pa-cln3.140,NaN,L199Pa or 7_Lauronen_1999,cln3.001,c.461-280_677+382del,NaN,NaN,Protracted juvenile,5.5,FP / CL,Finland,NaN,NaN,"IBDC, 1995",7553855,NaN,NaN
1,Pa-cln3.140,NaN,L199Pa 7_Lauronen_1999,cln3.002,c.(790+1_791-1)_(1056+1_1057-1)del,NaN,NaN,Protracted juvenile,5.5,FP / CL,Finland,NaN,NaN,"Munroe et al., 1997",9151312,"PMID updated June 2025, as wrong paper selected",Kousi 2012 says breakpoints not determined. c....
2,Pa-cln3.141,NaN,"L198Pa or 8_Lauronen et al., 1999",cln3.001,c.461-280_677+382del,NaN,NaN,Protracted juvenile,7,FP / CL,Finland,NaN,NaN,"IBDC, 1995",7553855,NaN,NaN
3,Pa-cln3.141,NaN,"L198Pa or 8_Lauronen et al., 1999",cln3.004,c.533+1G>C,NaN,NaN,Protracted juvenile,7,FP / CL,Finland,NaN,NaN,"Munroe et al., 1997",9311735,NaN,NaN
4,Pa-cln3.142,NaN,NCL39.3,cln3.001,c.461-280_677+382del,NaN,NaN,juvenile,NaN,NaN,Morocco,NaN,NaN,"IBDC, 1995",7553855,NaN,NaN

In [63]:
# ============================================================
# CLN3 PATIENT DATA QUALITY ANALYSIS
# ============================================================

print("=" * 60)
print("CLN3 PATIENT DATA ANALYSIS")
print("=" * 60)

print("\nTotal rows:")
print(len(cln3_patient))

print("\nExact duplicate rows:")
print(cln3_patient.duplicated().sum())

print("\nUnique Patient Identifiers:")
print(cln3_patient["DB Patient ID"].nunique())

print("\nMissing Patient Identifiers:")
print(cln3_patient["DB Patient ID"].isna().sum())

print("\nUnique Mutation Numbers:")
print(cln3_patient["mutation number"].nunique())

print("\nMissing Mutation Numbers:")
print(cln3_patient["mutation number"].isna().sum())

============================================================
CLN3 PATIENT DATA ANALYSIS
============================================================

Total rows:
603

Exact duplicate rows:
105

Unique Patient Identifiers:
305

Missing Patient Identifiers:
0

Unique Mutation Numbers:
130

Missing Mutation Numbers:
67

In [64]:
# ============================================================
# CLN3 MUTATION MATCHING ANALYSIS
# ============================================================

# Clean text values first
patient_mutations = (
    cln3_patient["mutation number"]
    .dropna()
    .astype(str)
    .str.strip()
)

mutation_identifiers = (
    cln3_mutation["Identifier"]
    .dropna()
    .astype(str)
    .str.strip()
)

patient_unique_mutations = set(patient_mutations.unique())
mutation_unique_identifiers = set(mutation_identifiers.unique())

matched_mutations = (
    patient_unique_mutations
    & mutation_unique_identifiers
)

unmatched_mutations = (
    patient_unique_mutations
    - mutation_unique_identifiers
)

print("=" * 60)
print("CLN3 MUTATION MATCHING")
print("=" * 60)

print("\nUnique mutations in Patient Dataset:")
print(len(patient_unique_mutations))

print("\nUnique identifiers in Mutation Dataset:")
print(len(mutation_unique_identifiers))

print("\nMatched mutations:")
print(len(matched_mutations))

print("\nUnmatched patient mutations:")
print(len(unmatched_mutations))

print("\nSample unmatched mutations:")
print(list(unmatched_mutations)[:20])

============================================================
CLN3 MUTATION MATCHING
============================================================

Unique mutations in Patient Dataset:
129

Unique identifiers in Mutation Dataset:
138

Matched mutations:
125

Unmatched patient mutations:
4

Sample unmatched mutations:
['cln3.105', 'cln3.033', 'wildtype', 'cln3.034']

In [65]:
# ============================================================
# CLEAN CLN3 PATIENT DATASET
# ============================================================

print("Before removing exact duplicates:", len(cln3_patient))

# Remove exact duplicate rows
cln3_patient_clean = cln3_patient.drop_duplicates().copy()

# Remove completely empty rows again
cln3_patient_clean = cln3_patient_clean.dropna(how="all")

# Clean Patient ID
cln3_patient_clean["DB Patient ID"] = (
    cln3_patient_clean["DB Patient ID"]
    .astype("string")
    .str.strip()
)

# Clean mutation number
cln3_patient_clean["mutation number"] = (
    cln3_patient_clean["mutation number"]
    .astype("string")
    .str.strip()
    .str.lower()
)

print("After removing exact duplicates:", len(cln3_patient_clean))
print("Exact duplicates remaining:", cln3_patient_clean.duplicated().sum())

print("\nUnique Patient IDs:",
      cln3_patient_clean["DB Patient ID"].nunique())

print("Missing Patient IDs:",
      cln3_patient_clean["DB Patient ID"].isna().sum())

Before removing exact duplicates: 603
After removing exact duplicates: 498
Exact duplicates remaining: 0

Unique Patient IDs: 305
Missing Patient IDs: 0

In [66]:
# ============================================================
# CLEAN CLN3 MUTATION DATASET
# ============================================================

print("Original mutation rows:", len(cln3_mutation))

# Remove completely empty rows
cln3_mutation_clean = cln3_mutation.dropna(how="all").copy()

# Clean Identifier
cln3_mutation_clean["Identifier"] = (
    cln3_mutation_clean["Identifier"]
    .astype("string")
    .str.strip()
    .str.lower()
)

# Remove rows where Identifier is missing
cln3_mutation_clean = cln3_mutation_clean.dropna(
    subset=["Identifier"]
)

# Remove duplicate mutation identifiers
# Keep first occurrence
cln3_mutation_clean = (
    cln3_mutation_clean
    .drop_duplicates(
        subset=["Identifier"],
        keep="first"
    )
)

print("Cleaned mutation rows:", len(cln3_mutation_clean))

print("Missing Identifiers:",
      cln3_mutation_clean["Identifier"].isna().sum())

print("Unique Identifiers:",
      cln3_mutation_clean["Identifier"].nunique())

print("Duplicate Identifiers:",
      cln3_mutation_clean["Identifier"].duplicated().sum())

Original mutation rows: 138
Cleaned mutation rows: 138
Missing Identifiers: 0
Unique Identifiers: 138
Duplicate Identifiers: 0

In [67]:
# ============================================================
# MERGE CLN3 PATIENT + MUTATION DATA
# ============================================================

cln3_merged = cln3_patient_clean.merge(

    cln3_mutation_clean,

    how="left",

    left_on="mutation number",

    right_on="Identifier",

    suffixes=(
        "_patient",
        "_mutation"
    )
)

print("=" * 60)
print("CLN3 MERGED DATASET")
print("=" * 60)

print("\nMerged dataset shape:")
print(cln3_merged.shape)

print("\nPatients with matched mutation information:")

matched_count = cln3_merged["Identifier"].notna().sum()

print(matched_count)

print("\nPatients WITHOUT matched mutation information:")

unmatched_count = cln3_merged["Identifier"].isna().sum()

print(unmatched_count)

============================================================
CLN3 MERGED DATASET
============================================================

Merged dataset shape:
(498, 35)

Patients with matched mutation information:
427

Patients WITHOUT matched mutation information:
71

In [68]:
# ============================================================
# ADD DISEASE SUBTYPE
# ============================================================

cln3_merged["Disease_Subtype"] = "CLN3"

print(
    cln3_merged["Disease_Subtype"]
    .unique()
)

<StringArray>
['CLN3']
Length: 1, dtype: str

In [69]:
# ============================================================
# SAVE CLN3 PROCESSED DATASET
# ============================================================

import os

processed_folder = "../data/processed"

os.makedirs(
    processed_folder,
    exist_ok=True
)

output_path = (
    "../data/processed/"
    "cln3_processed.csv"
)

cln3_merged.to_csv(
    output_path,
    index=False
)

print("CLN3 processed dataset saved successfully!")
print("Location:", output_path)

print("\nFinal Dataset Shape:")
print(cln3_merged.shape)

CLN3 processed dataset saved successfully!
Location: ../data/processed/cln3_processed.csv

Final Dataset Shape:
(498, 36)